Repository potathon/Team5-FE, pull requests merged in 2024-07, with the labels that each got.

#1 chore : 프로젝트 초기 설정
  .eslintrc.js
  .prettierrc.js
  babel.config.js
  package-lock.json
  package.json
  public/index.html
  src/index.js
  src/reportWebVitals.js
  tsconfig.json
Labels: chore

#2 feat : 파일구조 초기 설정
  src/assets/logo192.png
  src/assets/logo512.png
  src/components/button/index.css
  src/components/button/index.tsx
  src/components/card/index.css
  src/components/card/index.tsx
  src/components/tag/index.css
  src/components/tag/index.tsx
  src/pages/home/index.css
  src/pages/home/index.tsx
  src/pages/main/index.css
  src/pages/main/index.tsx
  src/pages/makePost/index.css
  src/pages/makePost/index.tsx
Labels: feat

#3 feat: makePost 스크린 작업 및 tag 컴포넌트화
  package-lock.json
  package.json
  src/App.css
  src/App.js
  src/components/button/index.tsx
  src/components/card/index.tsx
  src/components/tag/index.css
  src/components/tag/index.tsx
  src/pages/home/index.tsx
  src/pages/main/index.tsx
  src/pages/makePost/index.css
  src/pages/makePost/index.tsx
Labels: feat

#4 Add images
  src/assets/edit.png
  src/assets/laundry.png
  src/assets/laundry_blue.png
  src/assets/location.png
  src/assets/logo.png
  src/assets/participants.png
  src/assets/shopping.png
  src/assets/shopping_pink.png
  src/assets/time.png
  src/pages/main/index.css
  src/pages/main/index.tsx
Labels: Image

#5 feat: home 스크린, main 스크린 기본 구현 및 navigation추가, card 컴포넌트 구현
  package-lock.json
  package.json
  public/assets/edit.png
  public/assets/laundry.png
  public/assets/laundry_blue.png
  public/assets/location.png
  public/assets/logo.png
  public/assets/participants.png
  public/assets/shopping.png
  public/assets/shopping_pink.png
  public/assets/time.png
  src/App.js
  src/assets/logo192.png
  src/assets/logo512.png
  src/components/card/index.css
  src/components/card/index.tsx
  src/pages/home/index.css
  src/pages/home/index.tsx
  src/pages/main/index.css
  src/pages/main/index.tsx
Labels: feat

#11 feat : 모달 컴포넌트 생성
  src/components/button/index.css
  src/components/button/index.tsx
  src/components/card/index.css
  src/components/card/index.tsx
  src/components/modal/index.css
  src/components/modal/index.tsx
Labels: feat

#15 feat: 백앤드와 main 변수명 맞춤 및 네비게이션 연결
  package-lock.json
  package.json
  src/App.js
  src/pages/main/index.tsx
  src/pages/makePost/index.tsx
Labels: feat

#19 refactor : makePost 컴포넌트 추가 및 css수정
  src/components/header/index.css
  src/pages/makePost/index.css
  src/pages/makePost/index.tsx
Labels: feat

#27 refactor: home css 수정
  src/components/card/index.css
  src/components/card/index.tsx
  src/pages/main/index.css
  src/pages/main/index.tsx
Labels: feat
